import os

ENVIRONMENT = os.getenv('ENVIRONMENT')
SECRET_KEY = os.getenv('SECRET_KEY')
ENCRYPTION_TYPE = os.getenv('ENCRYPTION_TYPE')
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')